
stages:
  - test
  - build
  - testdelivery
  - deploy
  - cleanup


test_ubuntu1604:
  stage: test
  image: ubuntu:16.04
  script:
  - apt update
  - apt install -yyq python3-pip pylint pylint3 clang-format-3.8 curl
  - pip3 install colorlog
  - pip3 install autopep8
  - curl https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py > /usr/bin/cpplint
  - chmod a+x /usr/bin/cpplint
  - ./codebeautifier --help
  - ./unittest.sh ./codebeautifier
  - ./codebeautifier check codebeautifier
  - ./codebeautifier check setup.py

test_ubuntu1510:
  stage: test
  image: ubuntu:15.10
  script:
  - apt update
  - apt install -yyq python3-pip pylint pylint3 clang-format-3.7 curl
  - pip3 install colorlog
  - pip3 install autopep8
  - curl https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py > /usr/bin/cpplint
  - chmod a+x /usr/bin/cpplint
  - chmod a+x /usr/bin/cpplint
  - ./codebeautifier --help
  - ./unittest.sh ./codebeautifier
  - ./codebeautifier check codebeautifier
  - ./codebeautifier check setup.py

build_docker:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker --version
  - docker build -t registry.gitlab.com/ercom/codebeautifier:${CI_BUILD_REF_NAME} .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/ercom/codebeautifier:${CI_BUILD_REF_NAME}

test_docker:
  stage: testdelivery
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker --version
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker run registry.gitlab.com/ercom/codebeautifier:${CI_BUILD_REF_NAME} unittest
  - docker run -v ${PWD}:/var/input registry.gitlab.com/ercom/codebeautifier:${CI_BUILD_REF_NAME} check codebeautifier
  - docker run -v ${PWD}:/var/input registry.gitlab.com/ercom/codebeautifier:${CI_BUILD_REF_NAME} check setup.py

deploy_docker:
  stage: deploy
  image: docker:latest
  services:
  - docker:dind
  only:
  - master
  script:
  - docker --version
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker pull registry.gitlab.com/ercom/codebeautifier:${CI_BUILD_REF_NAME}
  - docker tag registry.gitlab.com/ercom/codebeautifier:${CI_BUILD_REF_NAME} registry.gitlab.com/ercom/codebeautifier:latest
  - docker push registry.gitlab.com/ercom/codebeautifier:latest

cleanup_docker:
  when: always
  stage: cleanup
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker --version
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker pull hello-world
  - docker tag hello-world registry.gitlab.com/ercom/codebeautifier:${CI_BUILD_REF_NAME}
  - docker push registry.gitlab.com/ercom/codebeautifier:${CI_BUILD_REF_NAME}

